spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wolox?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


    
server:
  error:
    whitelabel:
      enabled: false